development:
  adapter: postgresql
  database: notearkiv-development
  pool: 5
  username: test

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: notearkiv-prod
  pool: 5
  username: test
