# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: postgresql
  database: notearkiv-development
  pool: 5
  username: test

test:
  adapter: postgresql
  database: notearkiv-test
  pool: 5
  username: test

production:
  adapter: postgresql
  database: notearkiv-prod
  pool: 5
  username: test
